# Generated by Django 4.2.7 on 2026-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_announcement_created_by_announcement_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of related object', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_model',
            field=models.CharField(blank=True, help_text='Model name of related object', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('payment_approved', 'Payment Approved'), ('attendance_alert', 'Attendance Alert'), ('meeting_reminder', 'Meeting Reminder'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_cancelled', 'Meeting Cancelled'), ('welfare_alert', 'Welfare Alert'), ('welfare_event', 'Welfare Event'), ('welfare_target', 'Welfare Target Reached'), ('compliance_alert', 'Compliance Alert'), ('compliance_update', 'Compliance Update'), ('system', 'System Notification'), ('announcement', 'Announcement'), ('member_registered', 'Member Registered'), ('report_ready', 'Report Ready'), ('chat_message', 'Chat Message')], max_length=50),
        ),
    ]
