# Generated by Django 4.2.7 on 2026-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_chatroom_options_chatmessage_read_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
