# Generated by Django 6.0.7 on 2026-07-29 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to='members.member')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Alert',
                'verbose_name_plural': 'Compliance Alerts',
                'db_table': 'compliance_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('payment', 'Payment'), ('attendance', 'Attendance'), ('combined', 'Combined')], max_length=20)),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage required', max_digits=5)),
                ('grace_period_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_rules', to='finance.paymentcategory')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'compliance_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('green', 'Eligible'), ('yellow', 'Warning'), ('red', 'Not Eligible')], default='green', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('payment_compliance', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('attendance_compliance', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='members.member')),
            ],
            options={
                'verbose_name': 'Compliance Score',
                'verbose_name_plural': 'Compliance Scores',
                'db_table': 'compliance_scores',
                'ordering': ['-score'],
            },
        ),
    ]
