# Generated by Django 4.2.7 on 2026-07-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('green', 'Eligible'), ('yellow', 'Warning'), ('red', 'Not Eligible')], default='green', help_text='Current compliance status', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=100.0, help_text='Overall compliance score (0-100)', max_digits=5)),
                ('payment_compliance', models.DecimalField(decimal_places=2, default=100.0, help_text='Payment compliance score', max_digits=5)),
                ('attendance_compliance', models.DecimalField(decimal_places=2, default=100.0, help_text='Attendance compliance score', max_digits=5)),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Last time compliance was checked')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='List of active warnings')),
                ('history', models.JSONField(blank=True, default=list, help_text='Historical compliance data')),
                ('member', models.OneToOneField(help_text='Member this score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='members.member')),
            ],
            options={
                'verbose_name': 'Compliance Score',
                'verbose_name_plural': 'Compliance Scores',
                'db_table': 'compliance_scores',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the compliance rule', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rule')),
                ('rule_type', models.CharField(choices=[('payment', 'Payment'), ('attendance', 'Attendance'), ('combined', 'Combined')], help_text='Type of compliance rule', max_length=20)),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage required (for attendance rules)', max_digits=5)),
                ('grace_period_days', models.IntegerField(default=30, help_text='Grace period in days before compliance is affected')),
                ('penalty_points', models.DecimalField(decimal_places=2, default=10.0, help_text='Points deducted for non-compliance', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('order', models.IntegerField(default=0, help_text='Order in which rules are applied')),
                ('target_category', models.ForeignKey(blank=True, help_text='Payment category this rule applies to (if payment rule)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_rules', to='finance.paymentcategory')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'compliance_rules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('members', 'Members Report'), ('warnings', 'Warnings Report')], max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Report data')),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance_reports/')),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('payment_overdue', 'Payment Overdue'), ('attendance_low', 'Low Attendance'), ('compliance_low', 'Low Compliance Score'), ('status_changed', 'Status Changed'), ('warning_issued', 'Warning Issued')], help_text='Type of alert', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Alert priority level', max_length=20)),
                ('message', models.TextField(help_text='Alert message')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the alert is resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about resolution')),
                ('member', models.ForeignKey(help_text='Member this alert is for', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to='members.member')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Alert',
                'verbose_name_plural': 'Compliance Alerts',
                'db_table': 'compliance_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
