# Generated by Django 4.2.7 on 2026-07-29 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_created_by_payment_updated_by_and_more'),
        ('members', '0002_member_created_by_member_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancescore',
            name='history',
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancealert',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancescore',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancescore',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='alert_type',
            field=models.CharField(choices=[('payment_overdue', 'Payment Overdue'), ('attendance_low', 'Low Attendance'), ('compliance_low', 'Low Compliance Score'), ('status_changed', 'Status Changed'), ('warning_issued', 'Warning Issued')], max_length=30),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active'),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to='members.member'),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_compliance_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='grace_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='min_attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='penalty_points',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='rule_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('attendance', 'Attendance'), ('combined', 'Combined')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_rules', to='finance.paymentcategory'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='attendance_compliance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created'),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active'),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='members.member'),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='payment_compliance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='status',
            field=models.CharField(choices=[('green', 'Eligible'), ('yellow', 'Warning'), ('red', 'Not Eligible')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='compliancescore',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
