# Generated by Django 4.2.7 on 2026-07-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='How the payment was made', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, help_text='Transaction reference number', max_length=50)),
                ('external_ref', models.CharField(blank=True, help_text='External reference (M-Pesa code, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the payment was verified', null=True)),
                ('receipt_url', models.URLField(blank=True, help_text='URL to digital receipt')),
                ('receipt_file', models.FileField(blank=True, help_text='Uploaded receipt file', null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the payment category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, help_text='Default amount for this category', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-Time'), ('quarterly', 'Quarterly'), ('weekly', 'Weekly')], default='one-time', help_text='How often this payment is required', max_length=20)),
                ('is_mandatory_for_welfare', models.BooleanField(default=False, help_text='Whether this payment is required for welfare eligibility')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('color', models.CharField(default='primary', help_text='Color for displaying this category', max_length=20)),
                ('icon', models.CharField(default='fa-money-bill', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
                'db_table': 'payment_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('member', 'Member Report'), ('category', 'Category Report'), ('period', 'Period Report')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/payments/')),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Report',
                'verbose_name_plural': 'Payment Reports',
                'db_table': 'payment_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_type', models.CharField(choices=[('overdue', 'Overdue'), ('upcoming', 'Upcoming'), ('manual', 'Manual')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.paymentcategory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='members.member')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'db_table': 'payment_reminders',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/pdf/')),
                ('html_content', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'db_table': 'payment_receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(help_text='Payment category', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.paymentcategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(help_text='Member making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(help_text='User who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
