# Generated by Django 6.0.7 on 2026-07-29 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BereavementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deceased_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('date_of_death', models.DateField()),
                ('collection_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('disbursed', 'Disbursed')], default='active', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('disbursement_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bereavements', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The member who is bereaved', on_delete=django.db.models.deletion.CASCADE, related_name='bereavement_events', to='members.member')),
            ],
            options={
                'verbose_name': 'Bereavement Event',
                'verbose_name_plural': 'Bereavement Events',
                'db_table': 'bereavement_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereavementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_public_contribution', models.BooleanField(default=True)),
                ('contributor_name', models.CharField(blank=True, max_length=200)),
                ('contributor_phone', models.CharField(blank=True, max_length=17)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bereavement_contributions', to='members.member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='welfare.bereavementevent')),
            ],
            options={
                'verbose_name': 'Bereavement Contribution',
                'verbose_name_plural': 'Bereavement Contributions',
                'db_table': 'bereavement_contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
