# Generated by Django 4.2.7 on 2026-07-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('request_type', models.CharField(choices=[('bereavement', 'Bereavement Support'), ('medical', 'Medical Assistance'), ('education', 'Education Support'), ('emergency', 'Emergency Fund'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='welfare_docs/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_requests', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_requests', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Welfare Request',
                'verbose_name_plural': 'Welfare Requests',
                'db_table': 'welfare_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('fund_type', models.CharField(choices=[('general', 'General Welfare Fund'), ('emergency', 'Emergency Fund'), ('bereavement', 'Bereavement Fund'), ('development', 'Development Fund')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Welfare Fund',
                'verbose_name_plural': 'Welfare Funds',
                'db_table': 'welfare_funds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BereavementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('event_code', models.CharField(blank=True, help_text='Auto-generated event code', max_length=20, unique=True)),
                ('deceased_name', models.CharField(help_text='Full name of the deceased', max_length=200)),
                ('relationship', models.CharField(help_text='Relationship to the member', max_length=100)),
                ('date_of_death', models.DateField(help_text='Date of death')),
                ('date_of_burial', models.DateField(blank=True, help_text='Date of burial', null=True)),
                ('collection_target', models.DecimalField(decimal_places=2, help_text='Target amount to collect', max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('disbursement_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the event')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bereavements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The member who is bereaved', on_delete=django.db.models.deletion.CASCADE, related_name='bereavement_events', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bereavement Event',
                'verbose_name_plural': 'Bereavement Events',
                'db_table': 'bereavement_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereavementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_type', models.CharField(choices=[('member', 'Member Contribution'), ('public', 'Public Contribution'), ('group', 'Group Contribution'), ('other', 'Other')], default='member', max_length=20)),
                ('is_public_contribution', models.BooleanField(default=True)),
                ('contributor_name', models.CharField(blank=True, help_text='Name for public contributions', max_length=200)),
                ('contributor_phone', models.CharField(blank=True, max_length=17)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('contributor', models.ForeignKey(blank=True, help_text='Member who contributed (if member)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bereavement_contributions', to='members.member')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='welfare.bereavementevent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bereavement Contribution',
                'verbose_name_plural': 'Bereavement Contributions',
                'db_table': 'bereavement_contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
