# Generated by Django 4.2.7 on 2026-07-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('title', models.CharField(help_text='Meeting title/agenda topic', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the meeting')),
                ('date', models.DateTimeField(help_text='Date and time of the meeting')),
                ('venue', models.CharField(help_text='Physical or virtual meeting location', max_length=200)),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda items')),
                ('minutes_text', models.TextField(blank=True, help_text='Meeting minutes in text format')),
                ('minutes_url', models.URLField(blank=True, help_text='URL to uploaded minutes document')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for attendance', max_length=255)),
                ('created_by', models.ForeignKey(help_text='User who created this meeting', on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('content', models.TextField(help_text='Full minutes content')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the meeting')),
                ('decisions', models.JSONField(blank=True, default=list, help_text='List of decisions made')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='List of action items')),
                ('attendees_count', models.IntegerField(default=0, help_text='Number of attendees')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, help_text='Uploaded minutes file', null=True, upload_to='minutes/')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved these minutes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(help_text='Meeting these minutes belong to', on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
                'verbose_name_plural': 'Meeting Minutes',
                'db_table': 'meeting_minutes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], default='absent', help_text='Attendance status', max_length=20)),
                ('check_in_method', models.CharField(blank=True, choices=[('qr', 'QR Code'), ('manual', 'Manual'), ('gps', 'GPS'), ('fingerprint', 'Fingerprint')], help_text='How the member checked in', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Time the member checked in', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Time the member checked out', null=True)),
                ('gps_coordinates', models.CharField(blank=True, help_text='GPS coordinates of check-in', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of check-in device', null=True)),
                ('device_info', models.CharField(blank=True, help_text='Device information', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='Meeting this attendance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('member', models.ForeignKey(help_text='Member whose attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'member')},
            },
        ),
    ]
